// const { GoogleSpreadsheet } = require('google-spreadsheet');

// Initialize the sheet - doc ID is the long id in the sheets URL


// export const traerPreguntas = async() => {
//     const doc = new GoogleSpreadsheet('1dKW233891O-uHdn5I7MoM9iKilK5dz-jdgA5mqPZN0U');
    
//     // Initialize Auth - see https://theoephraim.github.io/node-google-spreadsheet/#/getting-started/authentication
//     await doc.useServiceAccountAuth({
//       // env var values are copied from service account credentials generated by google
//       // see "Authentication" section in docs for more info
//       client_email: "liberadosintegration@liberados-358520.iam.gserviceaccount.com",
//       private_key: "AIzaSyAJ5agRyM7hC3gOq19aEcVcd6VowRyBlIk",
      

//     });

//     const sheet = doc.sheetsByIndex[0]; // or use doc.sheetsById[id] or doc.sheetsByTitle[title]
//     console.log(sheet.getCell(2,2));

// }


/*
import { google } from "googleapis";
import React from "react";
console.log("Hola ")
const googleSheets = google.sheets({version: "v4"});

const spreadsheetId = "1dKW233891O-uHdn5I7MoM9iKilK5dz-jdgA5mqPZN0U";

const metaData = await googleSheets.spreadsheets.get({
    spreadsheetId
})

const getRows = await googleSheets.spreadsheets.values.get({
    spreadsheetId, 
    range: "Sheet1"

});

console.log(getRows.data)
*/
